<?php

/*
 * This file is part of ibrand/laravel-shopping-cart.
 *
 * (c) iBrand <https://www.ibrand.cc>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use iBrand\ShoppingCart\Cart;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class DatabaseCartTest extends Orchestra\Testbench\TestCase
{
    use DatabaseMigrations;

    use CartTestTrait;

    protected $cart;

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('ibrand.cart', require __DIR__.'/../src/config.php');
        $app['config']->set('ibrand.cart.storage', iBrand\Shoppingcart\Storage\DatabaseStorage::class);

        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
    }

    protected function loadMigrationsFrom($app)
    {
        $this->artisan('migrate', ['--database' => 'testbench']);
    }

    protected function getPackageProviders($app)
    {
        return [iBrand\Shoppingcart\ServiceProvider::class];
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->loadMigrationsFrom(__DIR__.'/database');

        //dd($this->app['config']->get('database'));
        $this->cart = $this->app['cart'];
    }
}
