<?php

/*
 * This file is part of ibrand/laravel-shopping-cart.
 *
 * (c) iBrand <https://www.ibrand.cc>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Illuminate\Support\Collection;
use Mockery as m;
use iBrand\ShoppingCart\Cart;

class SessionCartTest extends Orchestra\Testbench\TestCase
{

    use CartTestTrait;

    protected $cart;

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('ibrand.cart', require __DIR__ . '/../src/config.php');
        $app['config']->set('ibrand.cart.storage', iBrand\Shoppingcart\Storage\SessionStorage::class);
    }

    protected function getPackageProviders($app)
    {
        return [iBrand\Shoppingcart\ServiceProvider::class];
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->cart = $this->app['cart'];
    }


}
